### ISSUE TITLE
Add cumulative total columns and persist both fields

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2#16]

**Comment by tokland** [comment]
I've added the cumulative column total and hidden the last field for both cumulative totals, since it makes no sense to repeat the last value. An example with the 4 totals enabled:

![cumulative-row-and-column](https://cloud.githubusercontent.com/assets/24643/15297079/a57cbc08-1b98-11e6-8fb7-b0a6e72061c2.png)
