### ISSUE TITLE
Create our own deploy system

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/dhis2#23]

**Comment by tokland** [comment]
I've been able to create a custom WAR that takes our custom local JARs instead of the published in the repositories. See https://github.com/EyeSeeTea/dhis2/wiki/Deploy

Now the custom web-pivot shows in both the webapp and the embedded items in the dashboards:

![dhis2-with-mods](https://cloud.githubusercontent.com/assets/24643/16268325/460b8714-388e-11e6-89ce-87d49daac248.png)
